$ kn service delete --all
Error: Internal error occurred: failed calling webhook "validation.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/resource-validation?timeout=10s": dial tcp 10.108.127.96:443: connect: connection refused
Error: Internal error occurred: failed calling webhook "validation.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/resource-validation?timeout=10s": dial tcp 10.108.127.96:443: connect: connection refused
Error: Internal error occurred: failed calling webhook "validation.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/resource-validation?timeout=10s": dial tcp 10.108.127.96:443: connect: connection refused
Error: Internal error occurred: failed calling webhook "validation.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/resource-validation?timeout=10s": dial tcp 10.108.127.96:443: connect: connection refused
Error: Internal error occurred: failed calling webhook "validation.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/resource-validation?timeout=10s": dial tcp 10.108.127.96:443: connect: connection refused
Error: Internal error occurred: failed calling webhook "validation.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/resource-validation?timeout=10s": dial tcp 10.108.127.96:443: connect: connection refused
Error: Internal error occurred: failed calling webhook "validation.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/resource-validation?timeout=10s": dial tcp 10.108.127.96:443: connect: connection refused
Error: Internal error occurred: failed calling webhook "validation.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/resource-validation?timeout=10s": dial tcp 10.108.127.96:443: connect: connection refused
Error: Internal error occurred: failed calling webhook "validation.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/resource-validation?timeout=10s": dial tcp 10.108.127.96:443: connect: connection refused
Error: Internal error occurred: failed calling webhook "validation.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/resource-validation?timeout=10s": dial tcp 10.108.127.96:443: connect: connection refused
